In [208]:
import xlrd
import numpy as np # basically matlab
import matplotlib.pyplot as plt # for plotting
book = xlrd.open_workbook('HockeyData2020.xlsx')
sheet = book.sheet_by_name('Sheet1')
x_train = [[sheet.cell_value(r, c) for c in range(sheet.ncols-1)] for r in range(sheet.nrows)]

# Profit !
#print(x_data)

#outputs
y_data = [sheet.cell_value(rw, 20) for rw in range(sheet.nrows)]
#y_data = np.zeros((302,2))
  

# sanity check
print('x_data shape =', np.shape(x_train))
print('y_data shape =',np.shape(y_data))
#x = np.concatenate((np.ones(n)[:, np.newaxis], x_train),1)

y_data

x_data shape = (302, 20)
y_data shape = (302,)


[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0

In [210]:
sheet2 = book.sheet_by_name('Sheet2')
x_test = [[sheet2.cell_value(r, c) for c in range(sheet2.ncols)] for r in range(sheet2.nrows)]

# Profit !
#print(x_test)

In [267]:
from keras.models import Sequential
from keras.layers import Dense, Dropout

# get dimensions
N = len(x_train) # number of data points
Nt = len(x_test)
input_dim = len(np.transpose(x_train)) # number of input features
output_dim = 1#len(np.transpose(y_data)) # number of output features #should be 2 #is NOT 2 #is 2 again
print(input_dim)

epochs = 100 # total number of epochs
neurons = 64 # number of neurons in the hidden layer

# define the model
model = Sequential()
model.add(Dense(neurons, input_dim=input_dim, activation='linear'))
model.add(Dense(neurons, activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(neurons, activation='relu'))
model.add(Dropout(0.5))



model.add(Dense(output_dim))

# set the loss function
model.compile(loss='mse', optimizer='adam', metrics=['accuracy']) #loss mean_squared_error? categorical?
model.summary()

20
Model: "sequential_35"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_111 (Dense)            (None, 64)                1344      
_________________________________________________________________
dense_112 (Dense)            (None, 64)                4160      
_________________________________________________________________
dropout_20 (Dropout)         (None, 64)                0         
_________________________________________________________________
dense_113 (Dense)            (None, 64)                4160      
_________________________________________________________________
dropout_21 (Dropout)         (None, 64)                0         
_________________________________________________________________
dense_114 (Dense)            (None, 1)                 65        
Total params: 9,729
Trainable params: 9,729
Non-trainable params: 0
________________________________________________

In [268]:
from keras.callbacks import ModelCheckpoint

#Save the best model.
model_checkpoint = ModelCheckpoint('best_NHL_model.hdf5', monitor='val_loss', save_best_only=True, period=1)
callbacks_list=[model_checkpoint]

model.fit(x=np.array(x_train),y=y_data, batch_size=31,epochs=epochs,verbose=1,validation_split=0.5,callbacks=callbacks_list)


Train on 151 samples, validate on 151 samples
Epoch 1/100
151/151 [==============================] - 1s 5ms/step - loss: 0.5124 - accuracy: 0.5497 - val_loss: 0.0922 - val_accuracy: 0.9272
Epoch 2/100
151/151 [==============================] - 0s 522us/step - loss: 0.3130 - accuracy: 0.6225 - val_loss: 0.1386 - val_accuracy: 0.8411
Epoch 3/100
151/151 [==============================] - 0s 370us/step - loss: 0.2195 - accuracy: 0.7483 - val_loss: 0.1400 - val_accuracy: 0.8344
Epoch 4/100
151/151 [==============================] - 0s 277us/step - loss: 0.2892 - accuracy: 0.6954 - val_loss: 0.1097 - val_accuracy: 0.8940
Epoch 5/100
151/151 [==============================] - 0s 277us/step - loss: 0.1968 - accuracy: 0.7748 - val_loss: 0.0774 - val_accuracy: 0.9272
Epoch 6/100
151/151 [==============================] - 0s 165us/step - loss: 0.1189 - accuracy: 0.8940 - val_loss: 0.0620 - val_accuracy: 0.9404
Epoch 7/100
151/151 [==============================] - 0s 159us/step - loss: 0.1321 - 

Epoch 57/100
151/151 [==============================] - 0s 192us/step - loss: 0.0199 - accuracy: 0.9868 - val_loss: 0.0280 - val_accuracy: 0.9669
Epoch 58/100
151/151 [==============================] - 0s 218us/step - loss: 0.0225 - accuracy: 0.9801 - val_loss: 0.0280 - val_accuracy: 0.9669
Epoch 59/100
151/151 [==============================] - 0s 159us/step - loss: 0.0248 - accuracy: 0.9868 - val_loss: 0.0278 - val_accuracy: 0.9669
Epoch 60/100
151/151 [==============================] - 0s 185us/step - loss: 0.0270 - accuracy: 0.9735 - val_loss: 0.0274 - val_accuracy: 0.9669
Epoch 61/100
151/151 [==============================] - 0s 326us/step - loss: 0.0212 - accuracy: 0.9868 - val_loss: 0.0274 - val_accuracy: 0.9669
Epoch 62/100
151/151 [==============================] - 0s 198us/step - loss: 0.0249 - accuracy: 0.9735 - val_loss: 0.0274 - val_accuracy: 0.9669
Epoch 63/100
151/151 [==============================] - 0s 205us/step - loss: 0.0141 - accuracy: 0.9868 - val_loss: 0.0273 -

In [269]:
model.load_weights('best_NHL_model.hdf5')
predict = model.predict(np.array(x_test))
predict
Y = np.exp(predict[:,0])/np.sum(np.exp(predict[:,0]))
Y

array([0.03181854, 0.03222312, 0.03137065, 0.03043288, 0.03112218,
       0.03811432, 0.03256638, 0.03874151, 0.03344462, 0.03267154,
       0.03056636, 0.0308563 , 0.03307328, 0.03306508, 0.0308068 ,
       0.03083062, 0.03171765, 0.03174674, 0.03239901, 0.03144203,
       0.03148781, 0.03564169, 0.03314522, 0.03123736, 0.03242435,
       0.03159436, 0.02986956, 0.03063376, 0.03210595, 0.03139471,
       0.03145551], dtype=float32)

In [270]:
teamlist = ["Anaheim Ducks",
"Arizona Coyotes",
"Boston Bruins",
"Buffalo Sabres",
"Calgary Flames",
"Carolina Hurricanes",
"Chicago Blackhawks",
"Colorado Avalanche",
"Columbus Blue Jackets",
"Dallas Stars",
"Detroit Red Wings",
"Edmonton Oilers",
"Florida Panthers",
"Los Angeles Kings",
"Minnesota Wild",
"Montréal Canadiens",
"Nashville Predators",
"New Jersey Devils",
"New York Islanders",
"New York Rangers",
"Ottawa Senators",
"Philadelphia Flyers",
"Pittsburgh Penguins",
"San Jose Sharks",
"St. Louis Blues",
"Tampa Bay Lightning",
"Toronto Maple Leafs",
"Vancouver Canucks",
"Vegas Golden Knights",
"Washington Capitals",
"Winnipeg Jets"]

In [271]:
Z = [x for _,x in sorted(zip(Y,teamlist))]
Z.reverse()
Z

['Colorado Avalanche',
 'Carolina Hurricanes',
 'Philadelphia Flyers',
 'Columbus Blue Jackets',
 'Pittsburgh Penguins',
 'Florida Panthers',
 'Los Angeles Kings',
 'Dallas Stars',
 'Chicago Blackhawks',
 'St. Louis Blues',
 'New York Islanders',
 'Arizona Coyotes',
 'Vegas Golden Knights',
 'Anaheim Ducks',
 'New Jersey Devils',
 'Nashville Predators',
 'Tampa Bay Lightning',
 'Ottawa Senators',
 'Winnipeg Jets',
 'New York Rangers',
 'Washington Capitals',
 'Boston Bruins',
 'San Jose Sharks',
 'Calgary Flames',
 'Edmonton Oilers',
 'Montréal Canadiens',
 'Minnesota Wild',
 'Vancouver Canucks',
 'Detroit Red Wings',
 'Buffalo Sabres',
 'Toronto Maple Leafs']

In [262]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(penalty='l1',solver='liblinear').fit(x_train, y_data)
clf.score(x_train, y_data)


#Basically, it's just guessing that EVERY team won't win, and 97% of the time, it's right! Oof.

0.9668874172185431

In [263]:
clf.predict(x_test)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [264]:
Y2 = clf.predict_proba(x_test)

In [265]:
Y2 = np.exp(Y2[:,1])/np.sum(np.exp(Y2[:,1]))
Y2 #By looking at the predicted probability of winning, we can rank the teams

array([0.03094652, 0.03281775, 0.03933487, 0.03099494, 0.03121264,
       0.03333515, 0.03156242, 0.03414463, 0.03741746, 0.03275891,
       0.03088451, 0.03100079, 0.03137327, 0.03168793, 0.03102611,
       0.03241704, 0.03176721, 0.03099688, 0.03146453, 0.03103621,
       0.03093454, 0.03315277, 0.03274378, 0.03096415, 0.03286064,
       0.03201883, 0.03138645, 0.0310925 , 0.03358903, 0.03158711,
       0.03149044])

In [266]:
Z2 = [x for _,x in sorted(zip(Y2,teamlist))]
Z2.reverse()
Z2

['Boston Bruins',
 'Columbus Blue Jackets',
 'Colorado Avalanche',
 'Vegas Golden Knights',
 'Carolina Hurricanes',
 'Philadelphia Flyers',
 'St. Louis Blues',
 'Arizona Coyotes',
 'Dallas Stars',
 'Pittsburgh Penguins',
 'Montréal Canadiens',
 'Tampa Bay Lightning',
 'Nashville Predators',
 'Los Angeles Kings',
 'Washington Capitals',
 'Chicago Blackhawks',
 'Winnipeg Jets',
 'New York Islanders',
 'Toronto Maple Leafs',
 'Florida Panthers',
 'Calgary Flames',
 'Vancouver Canucks',
 'New York Rangers',
 'Minnesota Wild',
 'Edmonton Oilers',
 'New Jersey Devils',
 'Buffalo Sabres',
 'San Jose Sharks',
 'Anaheim Ducks',
 'Ottawa Senators',
 'Detroit Red Wings']