<a href="https://colab.research.google.com/github/dwgb93/NHL-Stanley-Cup-Predictions/blob/main/2021/NHL2021_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import xlrd
import numpy as np # basically matlab
import matplotlib.pyplot as plt # for plotting
book = xlrd.open_workbook('HockeyData2021.xlsx')
sheet = book.sheet_by_name('Sheet1')
x_train = [[sheet.cell_value(r, c) for c in range(sheet.ncols-2)] for r in range(sheet.nrows)]

# Profit !
#print(x_data)

#outputs
y_data = [sheet.cell_value(rw, 20) for rw in range(sheet.nrows)]
y_categorical = [sheet.cell_value(rw, 21) for rw in range(sheet.nrows)]
#y_data = np.zeros((302,2))

# sanity check
print('x_data shape =', np.shape(x_train))
print('y_data shape =',np.shape(y_data))
#x = np.concatenate((np.ones(n)[:, np.newaxis], x_train),1)

y_categorical

x_data shape = (176, 20)
y_data shape = (176,)


['b',
 'a',
 'e',
 'a',
 'b',
 'a',
 'c',
 'a',
 'a',
 'a',
 'd',
 'a',
 'b',
 'c',
 'b',
 'a',
 'a',
 'e',
 'a',
 'a',
 'b',
 'a',
 'a',
 'b',
 'a',
 'b',
 'a',
 'a',
 'c',
 'c',
 'd',
 'b',
 'a',
 'a',
 'a',
 'a',
 'e',
 'b',
 'd',
 'c',
 'a',
 'b',
 'c',
 'a',
 'a',
 'b',
 'a',
 'b',
 'a',
 'd',
 'e',
 'b',
 'c',
 'a',
 'a',
 'a',
 'b',
 'b',
 'c',
 'b',
 'a',
 'a',
 'a',
 'a',
 'b',
 'b',
 'c',
 'a',
 'a',
 'a',
 'a',
 'e',
 'b',
 'c',
 'd',
 'a',
 'b',
 'a',
 'a',
 'a',
 'c',
 'b',
 'e',
 'a',
 'b',
 'b',
 'a',
 'a',
 'c',
 'a',
 'a',
 'a',
 'd',
 'a',
 'b',
 'a',
 'a',
 'a',
 'b',
 'a',
 'a',
 'a',
 'a',
 'b',
 'b',
 'a',
 'a',
 'e',
 'd',
 'c',
 'c',
 'b',
 'c',
 'a',
 'a',
 'a',
 'a',
 'b',
 'a',
 'a',
 'd',
 'b',
 'c',
 'e',
 'a',
 'b',
 'a',
 'b',
 'a',
 'b',
 'a',
 'a',
 'a',
 'a',
 'b',
 'a',
 'a',
 'b',
 'b',
 'c',
 'a',
 'd',
 'e',
 'c',
 'd',
 'a',
 'c',
 'b',
 'b',
 'b',
 'a',
 'b',
 'a',
 'c',
 'e',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'b',
 'a',
 'a',
 'a',
 'b',
 'a'

In [ ]:
sheet2 = book.sheet_by_name('Sheet2')
x_test = [[sheet2.cell_value(r, c) for c in range(sheet2.ncols)] for r in range(sheet2.nrows)]

# Profit !
print(x_test)

[[1.5580158054338478, -1.9840550878589673, 1.6636844874373882, 1.8132993694661321, 0.7569844647766205, -2.1467262865896686, 1.4995240554716294, 1.4285535333451918, 1.3794120177259797, 1.1807060721361502, 0.4449002273473756, -0.9142973921834366, 0.5313562255807787, 2.048217031471925, 1.5616843234157578, -0.18066593070662326, -0.7035151488798027, 1.9798899582857568, 2.0916801491867596, 1.5940630265421438], [0.5303883592966288, -0.28414859298482714, -1.295492018906163, 0.4408497329035191, 0.6077632227034914, -0.5095460248166552, 0.6653210072853704, 1.3302876468059153, 0.9230716954776478, 1.6644314673284961, 1.2182781926428137, -1.3714460882751527, 0.2690625473482312, 0.6827390104906447, 0.9546633045037911, 0.05238099467467587, 0.5548109759404369, 0.2250320787690674, -0.371355451555066, 0.956700285139316], [1.215473323388108, -1.0568333633821636, -0.027273516187498143, 1.1503364094316502, 1.1282177987146504, -0.957984443779551, -0.2551789079546399, 0.47864996346551414, -0.09698314248920939

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Dropout

# get dimensions
N = len(x_train) # number of data points
Nt = len(x_test)
input_dim = len(np.transpose(x_train)) # number of input features
output_dim = 1
print(input_dim)

epochs = 100 # total number of epochs
neurons = 64 # number of neurons in the hidden layer

# define the model
model = Sequential()
model.add(Dense(neurons, input_dim=input_dim, activation='linear'))
model.add(Dense(neurons, activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(neurons, activation='relu'))
model.add(Dropout(0.5))

model.add(Dense(output_dim))

# set the loss function
model.compile(loss='mse', optimizer='adam', metrics=['accuracy']) #loss mean_squared_error? categorical?
model.summary()

20
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 64)                1344      
_________________________________________________________________
dense_1 (Dense)              (None, 64)                4160      
_________________________________________________________________
dropout (Dropout)            (None, 64)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 64)                4160      
_________________________________________________________________
dropout_1 (Dropout)          (None, 64)                0         
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 65        
Total params: 9,729
Trainable params: 9,729
Non-trainable params: 0
___________________________________________________

In [ ]:
y_data

[0.25,
 0.0,
 1.0,
 0.0,
 0.25,
 0.0,
 0.5,
 0.0,
 0.0,
 0.0,
 0.75,
 0.0,
 0.25,
 0.5,
 0.25,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.25,
 0.0,
 0.0,
 0.25,
 0.0,
 0.25,
 0.0,
 0.0,
 0.5,
 0.5,
 0.75,
 0.25,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.25,
 0.75,
 0.5,
 0.0,
 0.25,
 0.5,
 0.0,
 0.0,
 0.25,
 0.0,
 0.25,
 0.0,
 0.75,
 1.0,
 0.25,
 0.5,
 0.0,
 0.0,
 0.0,
 0.25,
 0.25,
 0.5,
 0.25,
 0.0,
 0.0,
 0.0,
 0.0,
 0.25,
 0.25,
 0.5,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.25,
 0.5,
 0.75,
 0.0,
 0.25,
 0.0,
 0.0,
 0.0,
 0.5,
 0.25,
 1.0,
 0.0,
 0.25,
 0.25,
 0.0,
 0.0,
 0.5,
 0.0,
 0.0,
 0.0,
 0.75,
 0.0,
 0.25,
 0.0,
 0.0,
 0.0,
 0.25,
 0.0,
 0.0,
 0.0,
 0.0,
 0.25,
 0.25,
 0.0,
 0.0,
 1.0,
 0.75,
 0.5,
 0.5,
 0.25,
 0.5,
 0.0,
 0.0,
 0.0,
 0.0,
 0.25,
 0.0,
 0.0,
 0.75,
 0.25,
 0.5,
 1.0,
 0.0,
 0.25,
 0.0,
 0.25,
 0.0,
 0.25,
 0.0,
 0.0,
 0.0,
 0.0,
 0.25,
 0.0,
 0.0,
 0.25,
 0.25,
 0.5,
 0.0,
 0.75,
 1.0,
 0.5,
 0.75,
 0.0,
 0.5,
 0.25,
 0.25,
 0.25,
 0.0,
 0.25,
 0.0,
 0.5,
 1.0,
 0.0,
 0.0,
 0.0,
 0

In [ ]:
from keras.callbacks import ModelCheckpoint

#Save the best model.
model_checkpoint = ModelCheckpoint('best_NHL_model.hdf5', monitor='val_loss', save_best_only=True, save_freq='epoch')
callbacks_list=[model_checkpoint]

model.fit(x=np.array(x_train),y=np.array(y_data), batch_size=16,epochs=epochs,verbose=1,validation_split=0.5,callbacks=callbacks_list)


Epoch 1/100
6/6 [==============================] - 1s 51ms/step - loss: 0.0319 - accuracy: 0.5455 - val_loss: 0.0333 - val_accuracy: 0.5455
Epoch 2/100
6/6 [==============================] - 0s 13ms/step - loss: 0.0319 - accuracy: 0.5341 - val_loss: 0.0326 - val_accuracy: 0.5455
Epoch 3/100
6/6 [==============================] - 0s 14ms/step - loss: 0.0335 - accuracy: 0.5341 - val_loss: 0.0325 - val_accuracy: 0.5455
Epoch 4/100
6/6 [==============================] - 0s 15ms/step - loss: 0.0359 - accuracy: 0.5568 - val_loss: 0.0338 - val_accuracy: 0.5455
Epoch 5/100
6/6 [==============================] - 0s 12ms/step - loss: 0.0323 - accuracy: 0.5568 - val_loss: 0.0354 - val_accuracy: 0.5455
Epoch 6/100
6/6 [==============================] - 0s 12ms/step - loss: 0.0283 - accuracy: 0.5455 - val_loss: 0.0368 - val_accuracy: 0.5455
Epoch 7/100
6/6 [==============================] - 0s 13ms/step - loss: 0.0392 - accuracy: 0.5341 - val_loss: 0.0383 - val_accuracy: 0.5455
Epoch 8/100
6/6 [===

In [ ]:
model.load_weights('best_NHL_model.hdf5')
predict = model.predict(np.array(x_test))
predict
Y = np.exp(predict[:,0])/np.sum(np.exp(predict[:,0]))
Y

array([0.10185367, 0.06964913, 0.06821276, 0.05404677, 0.0504855 ,
       0.05443486, 0.05027695, 0.05130076, 0.06871438, 0.06024291,
       0.0806284 , 0.06432152, 0.05405093, 0.05608917, 0.06470984,
       0.05098245], dtype=float32)

In [ ]:
teamlist = ["Boston Bruins",
"Carolina Hurricanes",
"Colorado Avalanche",
"Edmonton Oilers",
"Florida Panthers",
"Minnesota Wild",
"Montréal Canadiens",
"Nashville Predators",
"New York Islanders",
"Pittsburgh Penguins",
"St. Louis Blues",
"Tampa Bay Lightning",
"Toronto Maple Leafs",
"Vegas Golden Knights",
"Washington Capitals",
"Winnipeg Jets"]

In [ ]:
Z = [x for _,x in sorted(zip(Y,teamlist))]
Z.reverse()
Z

['Boston Bruins',
 'St. Louis Blues',
 'Carolina Hurricanes',
 'New York Islanders',
 'Colorado Avalanche',
 'Washington Capitals',
 'Tampa Bay Lightning',
 'Pittsburgh Penguins',
 'Vegas Golden Knights',
 'Minnesota Wild',
 'Toronto Maple Leafs',
 'Edmonton Oilers',
 'Nashville Predators',
 'Winnipeg Jets',
 'Florida Panthers',
 'Montréal Canadiens']

In [ ]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(penalty='l2',solver='lbfgs').fit(x_train, y_categorical)
clf.score(x_train, y_categorical)


#Basically, it's just guessing that EVERY team won't win, and 58% of the time, it's right! Oof.

0.5795454545454546

In [ ]:
clf.predict(x_test)

array(['b', 'b', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'b', 'b', 'a', 'a',
       'a', 'a', 'a'], dtype='<U1')

In [ ]:
Y2_log = clf.predict_log_proba(x_test)
Y2 = clf.predict_proba(x_test)
Y2[:,-1]
#That's it - we want either want straight probabilities, or to exponentiate the log probabilities

array([0.22424592, 0.03291882, 0.15988081, 0.00153162, 0.00546801,
       0.00319555, 0.00842592, 0.06218794, 0.02139455, 0.01238015,
       0.03745299, 0.02631188, 0.01987706, 0.06445982, 0.01570699,
       0.01554335])

In [ ]:
Y2_log = np.exp(Y2_log[:,-1])
Y2_log #By looking at the predicted probability of winning, we can rank the teams
#This should be the same as the output of the cell above

array([0.22424592, 0.03291882, 0.15988081, 0.00153162, 0.00546801,
       0.00319555, 0.00842592, 0.06218794, 0.02139455, 0.01238015,
       0.03745299, 0.02631188, 0.01987706, 0.06445982, 0.01570699,
       0.01554335])

In [ ]:
Z2 = [x for _,x in sorted(zip(Y2_log,teamlist))]
Z2.reverse()
Z2

['Boston Bruins',
 'Colorado Avalanche',
 'Vegas Golden Knights',
 'Nashville Predators',
 'St. Louis Blues',
 'Carolina Hurricanes',
 'Tampa Bay Lightning',
 'New York Islanders',
 'Toronto Maple Leafs',
 'Washington Capitals',
 'Winnipeg Jets',
 'Pittsburgh Penguins',
 'Montréal Canadiens',
 'Florida Panthers',
 'Minnesota Wild',
 'Edmonton Oilers']

In [ ]:
losers = Y2[:,0]
Z3 = [x for _,x in sorted(zip(losers,teamlist))]
Z3.reverse()
Z3

['Florida Panthers',
 'Winnipeg Jets',
 'Nashville Predators',
 'Minnesota Wild',
 'New York Islanders',
 'Vegas Golden Knights',
 'Montréal Canadiens',
 'Edmonton Oilers',
 'Toronto Maple Leafs',
 'Washington Capitals',
 'Colorado Avalanche',
 'Tampa Bay Lightning',
 'Pittsburgh Penguins',
 'Carolina Hurricanes',
 'St. Louis Blues',
 'Boston Bruins']